name: Build all

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: "./build/workspaces/build_vs.bat"      
      - name: Tree
        run: tree
